---

- name: copy kubernetes.tar.gz
  copy: 'src=/data/kube{{ k8s_version }}.tar.gz dest=/root/ mode=0644'

- name: init every node 
  shell: 'cd /root && {{ item }}'
  with_items:
  - tar xvf kube{{ k8s_version }}.tar.gz
  - cd kube/shell && sh init.sh
  - yum install ntpdate -y
#  - ntpdate 0.asia.pool.ntp.org

